---
- hosts: servers

  tasks:

    - name: Create deployment directory
      file:
        path: /opt/tekton-demo
        state: directory

    - name: Copy docker compose file
      copy:
        src: ../files/docker-compose.yml
        dest: /opt/tekton-demo/docker-compose.yml

    - name: Copy environment file
      copy:
        src: ../files/app.env
        dest: /opt/tekton-demo/app.env

    - name: Stop existing application
      shell: |
        cd /opt/tekton-demo
        docker compose down
      ignore_errors: true

    - name: Pull latest image
      shell: |
        cd /opt/tekton-demo
        docker compose pull

    - name: Start application
      shell: |
        cd /opt/tekton-demo
        docker compose up -d